export const GET_DATA_SERVICE_REQUESTED = 'GET_DATA_SERVICE_REQUESTED' as const;
export const GET_DATA_SERVICE_SUCCEEDED = 'GET_DATA_SERVICE_SUCCEEDED' as const;
export const GET_DATA_SERVICE_FAILED = 'GET_DATA_SERVICE_FAILED' as const;
