export const GET_ORGANIZATIONS_REQUESTED = 'GET_ORGANIZATIONS_REQUESTED' as const;
export const GET_ORGANIZATIONS_SUCCEEDED = 'GET_ORGANIZATIONS_SUCCEEDED' as const;
export const GET_ORGANIZATIONS_FAILED = 'GET_ORGANIZATIONS_FAILED' as const;
