export const GET_DATASETS_REPORT_REQUESTED =
  'GET_DATASETS_REPORT_REQUESTED' as const;
export const GET_DATASETS_REPORT_SUCCEEDED =
  'GET_DATASETS_REPORT_SUCCEEDED' as const;
export const GET_DATASETS_REPORT_FAILED = 'GET_DATASETS_REPORT_FAILED' as const;

export const RESET_DATASETS_REPORT = 'RESET_DATASETS_REPORT' as const;
