export const GET_CONCEPTS_REQUESTED = 'GET_CONCEPTS_REQUESTED' as const;
export const GET_CONCEPTS_SUCCEEDED = 'GET_CONCEPTS_SUCCEEDED' as const;
export const GET_CONCEPTS_FAILED = 'GET_CONCEPTS_FAILED' as const;
export const RESET_CONCEPTS = 'RESET_CONCEPTS' as const;

export const GET_CONCEPTS_RELATIONS_REQUESTED =
  'GET_CONCEPTS_RELATIONS_REQUESTED' as const;
export const GET_CONCEPTS_RELATIONS_SUCCEEDED =
  'GET_CONCEPTS_RELATIONS_SUCCEEDED' as const;
export const GET_CONCEPTS_RELATIONS_FAILED =
  'GET_CONCEPTS_RELATIONS_FAILED' as const;
export const RESET_CONCEPTS_RELATIONS = 'RESET_CONCEPTS_RELATIONS' as const;
