export const GET_INFORMATION_MODEL_REQUESTED =
  'GET_INFORMATION_MODEL_REQUESTED' as const;
export const GET_INFORMATION_MODEL_SUCCEEDED =
  'GET_INFORMATION_MODEL_SUCCEEDED' as const;
export const GET_INFORMATION_MODEL_FAILED =
  'GET_INFORMATION_MODEL_FAILED' as const;

export const GET_INFORMATION_MODEL_RDF_REPRESENTATIONS_REQUESTED =
  'GET_INFORMATION_MODEL_RDF_REPRESENTATIONS_REQUESTED' as const;
export const GET_INFORMATION_MODEL_RDF_REPRESENTATIONS_SUCCEEDED =
  'GET_INFORMATION_MODEL_RDF_REPRESENTATIONS_SUCCEEDED' as const;
export const GET_INFORMATION_MODEL_RDF_REPRESENTATIONS_FAILED =
  'GET_INFORMATION_MODEL_RDF_REPRESENTATIONS_FAILED' as const;

export const RESET_INFORMATION_MODEL = 'RESET_INFORMATION_MODEL' as const;
