export const GET_SEARCH_SUGGESTIONS_REQUESTED =
  'GET_SEARCH_SUGGESTIONS_REQUESTED' as const;
export const GET_SEARCH_SUGGESTIONS_SUCCEEDED =
  'GET_SEARCH_SUGGESTIONS_SUCCEEDED' as const;
export const GET_SEARCH_SUGGESTIONS_FAILED =
  'GET_SEARCH_SUGGESTIONS_FAILED' as const;

export const RESET_SEARCH_SUGGESTIONS = 'RESET_SEARCH_SUGGESTIONS' as const;
