export const GET_EVENTS_REQUESTED = 'GET_EVENTS_REQUESTED' as const;
export const GET_EVENTS_SUCCEEDED = 'GET_EVENTS_SUCCEEDED' as const;
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED' as const;
export const RESET_EVENTS = 'RESET_EVENTS' as const;

export const GET_EVENTS_RELATIONS_REQUESTED = 'GET_EVENTS_RELATIONS_REQUESTED' as const;
export const GET_EVENTS_RELATIONS_SUCCEEDED = 'GET_EVENTS_RELATIONS_SUCCEEDED' as const;
export const GET_EVENTS_RELATIONS_FAILED = 'GET_EVENTS_RELATIONS_FAILED' as const;
export const RESET_EVENTS_RELATIONS = 'RESET_EVENTS_RELATIONS' as const;
