export const GET_AI_PROJECTS_REQUESTED = 'GET_AI_PROJECTS_REQUESTED' as const;
export const GET_AI_PROJECTS_SUCCEEDED = 'GET_AI_PROJECTS_SUCCEEDED' as const;
export const GET_AI_PROJECTS_FAILED = 'GET_AI_PROJECTS_FAILED' as const;
