apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-portal
  labels:
    app: fdk-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdk-portal
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-portal
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: fdk-portal
          image: fdk-portal
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
      restartPolicy: Always
