apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-portal
  labels:
    app: fdk-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdk-portal
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-portal
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: fdk-portal
          env:
            - name: CONTAINER_IMAGE
              value: ghcr.io/informasjonsforvaltning/fdk-portal:$(GIT_COMMIT_SHA)
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: common
                  key: NODE_ENV
            - name: FDK_PORTAL_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_PORTAL_BASE_URI
            - name: NAP_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: NAP_HOST
            - name: USE_DEMO_LOGO
              valueFrom:
                secretKeyRef:
                  name: common
                  key: USE_DEMO_LOGO
                  optional: true
            - name: SEARCH_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_SEARCH_SERVICE_BASE_URI
            - name: STATISTICS_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_STATISTICS_SERVICE_BASE_URI
            - name: CMS_API_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: CMS_API_BASE_URI
            - name: ORGANIZATION_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_ORGANIZATION_BFF_BASE_URI
            - name: ORGANIZATION_CATALOG_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: ORGANIZATION_CATALOG_BASE_URI
            - name: REPORT_API_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_REPORTS_BFF_BASE_URI
            - name: FDK_MQA_API_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_MQA_API_BASE_URI
            - name: FDK_REGISTRATION_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_REGISTRATION_BASE_URI
            - name: ADMIN_GUI_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: ADMIN_GUI_BASE_URI
            - name: INFORMATIONMODEL_HARVESTER_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_INFORMATIONMODEL_HARVESTER_BASE_URI
            - name: FDK_LOGGING_FUNCTION_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_LOGGING_FUNCTION_URI
            - name: NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: common
                  key: NAMESPACE
            - name: FDK_COMMUNITY_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_COMMUNITY_BASE_URI
            - name: FDK_CMS_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_CMS_BASE_URI
            - name: FDK_DATASET_PREVIEW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: common
                  key: FDK_DATASET_PREVIEW_API_KEY
            - name: FDK_USER_FEEDBACK_SERVICE_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_USER_FEEDBACK_SERVICE_BASE_URI
            - name: OIDC_ISSUER
              valueFrom:
                secretKeyRef:
                  name: sso
                  key: SSO_OIDC_ISSUER
            - name: AI_PROJECT_SERVICE_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: AI_PROJECT_SERVICE_BASE_URI
            - name: RESOURCE_API_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_RESOURCE_SERVICE_BASE_URI
            - name: CATALOG_PORTAL_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: CATALOG_PORTAL_BASE_URI
            - name: ACCESS_REQUEST_API_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: ACCESS_REQUEST_API_HOST
          image: fdk-portal
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
      restartPolicy: Always
