---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: fdk-portal
    newName: eu.gcr.io/digdir-fdk-infra/fdk-portal
    newTag: $(GIT_COMMIT_SHA)
