---
apiVersion: v1
kind: Service
metadata:
  labels:
    fdk.service: fdk-portal
  name: fdk-portal
spec:
  selector:
    app: fdk-portal
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
