export const SEARCH_TOPICS_REQUESTED = 'SEARCH_TOPICS_REQUESTED' as const;
export const SEARCH_TOPICS_SUCCEEDED = 'SEARCH_TOPICS_SUCCEEDED' as const;
export const SEARCH_TOPICS_FAILED = 'SEARCH_TOPICS_FAILED' as const;

export const GET_RECENT_POSTS_REQUESTED = 'GET_RECENT_POSTS_REQUESTED' as const;
export const GET_RECENT_POSTS_SUCCEEDED = 'GET_RECENT_POSTS_SUCCEEDED' as const;
export const GET_RECENT_POSTS_FAILED = 'GET_RECENT_POSTS_FAILED' as const;

export const RESET_TOPICS = 'RESET_TOPICS' as const;
export const RESET_POSTS = 'RESET_POSTS' as const;

export const SEARCH_REQUESTS_REQUESTED = 'SEARCH_REQUESTS_REQUESTED' as const;
export const SEARCH_REQUESTS_SUCCEEDED = 'SEARCH_REQUESTS_SUCCEEDED' as const;
export const SEARCH_REQUESTS_FAILED = 'SEARCH_REQUESTS_FAILED' as const;

export const GET_REQUEST_CATEGORY_REQUESTED =
  'GET_REQUEST_CATEGORY_REQUESTED' as const;
export const GET_REQUEST_CATEGORY_SUCCEEDED =
  'GET_REQUEST_CATEGORY_SUCCEEDED' as const;
export const GET_REQUEST_CATEGORY_FAILED =
  'GET_REQUEST_CATEGORY_FAILED' as const;
