export const GET_EVENT_TYPES_REQUESTED = 'GET_EVENT_TYPES_REQUESTED' as const;
export const GET_EVENT_TYPES_SUCCEEDED = 'GET_EVENT_TYPES_SUCCEEDED' as const;
export const GET_EVENT_TYPES_FAILED = 'GET_EVENT_TYPES_FAILED' as const;
export const RESET_EVENT_TYPES = 'RESET_EVENT_TYPES' as const;
