export const GET_ENTITIES_REQUESTED = 'GET_ENTITIES_REQUESTED' as const;
export const GET_ENTITIES_SUCCEEDED = 'GET_ENTITIES_SUCCEEDED' as const;
export const GET_ENTITIES_FAILED = 'GET_ENTITIES_FAILED' as const;
