export const GET_DATASETSSTATISTICS_REQUESTED = 'GET_DATASETSSTATISTICS_REQUESTED' as const;
export const GET_DATASETSSTATISTICS_SUCCEEDED = 'GET_DATASETSSTATISTICS_SUCCEEDED' as const;
export const GET_DATASETSSTATISTICS_FAILED = 'GET_DATASETSSTATISTICS_FAILED' as const;

export const RESET_DATASETSSTATISTICS = 'RESET_DATASETSSTATISTICS' as const;
