export const GET_RESOURCE_RELATIONS_REQUESTED =
  'GET_RESOURCE_RELATIONS_REQUESTED' as const;
export const GET_RESOURCE_RELATIONS_SUCCEEDED =
  'GET_RESOURCE_RELATIONS_SUCCEEDED' as const;
export const GET_RESOURCE_RELATIONS_FAILED =
  'GET_RESOURCE_RELATIONS_FAILED' as const;
export const RESET_RESOURCE_RELATIONS = 'RESET_RESOURCE_RELATIONS' as const;
