export const GET_ORGANIZATION_CATEGORIES_REQUESTED =
  'GET_ORGANIZATION_CATEGORIES_REQUESTED' as const;
export const GET_ORGANIZATION_CATEGORIES_SUCCEEDED =
  'GET_ORGANIZATION_CATEGORIES_SUCCEEDED' as const;
export const GET_ORGANIZATION_CATEGORIES_FAILED =
  'GET_ORGANIZATION_CATEGORIES_FAILED' as const;

export const SORT_ORGANIZATION_CATEGORIES =
  'SORT_ORGANIZATION_CATEGORIES' as const;
