export const GET_PUBLIC_SERVICES_AND_EVENTS_REQUESTED = 'GET_PUBLIC_SERVICES_AND_EVENTS_REQUESTED' as const;
export const GET_PUBLIC_SERVICES_AND_EVENTS_SUCCEEDED = 'GET_PUBLIC_SERVICES_AND_EVENTS_SUCCEEDED' as const;
export const GET_PUBLIC_SERVICES_AND_EVENTS_FAILED = 'GET_PUBLIC_SERVICES_AND_EVENTS_FAILED' as const;

export const RESET_PUBLIC_SERVICES_AND_EVENTS = 'RESET_PUBLIC_SERVICES_AND_EVENTS' as const;
