export const GET_ASSESSMENT_REQUESTED = 'GET_ASSESSMENT_REQUESTED' as const;
export const GET_ASSESSMENT_SUCCEEDED = 'GET_ASSESSMENT_SUCCEEDED' as const;
export const GET_ASSESSMENT_FAILED = 'GET_ASSESSMENT_FAILED' as const;
