export const LIST_ADMINISTRATIVE_UNITS_REQUESTED =
  'LIST_ADMINISTRATIVE_UNITS_REQUESTED' as const;
export const LIST_ADMINISTRATIVE_UNITS_SUCCEEDED =
  'LIST_ADMINISTRATIVE_UNITS_SUCCEEDED' as const;
export const LIST_ADMINISTRATIVE_UNITS_FAILED =
  'LIST_ADMINISTRATIVE_UNITS_FAILED' as const;

export const RESET_ADMINISTRATIVE_UNITS = 'RESET_ADMINISTRATIVE_UNITS' as const;
