export const GET_CONCEPT_REQUESTED = 'GET_CONCEPT_REQUESTED' as const;
export const GET_CONCEPT_SUCCEEDED = 'GET_CONCEPT_SUCCEEDED' as const;
export const GET_CONCEPT_FAILED = 'GET_CONCEPT_FAILED' as const;
