export const GET_REFERENCE_DATA_REQUESTED = 'GET_REFERENCE_DATA_REQUESTED' as const;
export const GET_REFERENCE_DATA_SUCCEEDED = 'GET_REFERENCE_DATA_SUCCEEDED' as const;
export const GET_REFERENCE_DATA_FAILED = 'GET_REFERENCE_DATA_FAILED' as const;
