export const GET_ORGANIZATIONS_CATALOG_REQUESTED =
  'GET_ORGANIZATIONS_CATALOG_REQUESTED' as const;
export const GET_ORGANIZATIONS_CATALOG_SUCCEEDED =
  'GET_ORGANIZATIONS_CATALOG_SUCCEEDED' as const;
export const GET_ORGANIZATIONS_CATALOG_FAILED =
  'GET_ORGANIZATIONS_CATALOG_FAILED' as const;

export const RESET_ORGANIZATIONS_CATALOG = 'RESET_ORGANIZATIONS' as const;
