export const GET_ORGANIZATION_REQUESTED = 'GET_ORGANIZATION_REQUESTED' as const;
export const GET_ORGANIZATION_SUCCEEDED = 'GET_ORGANIZATION_SUCCEEDED' as const;
export const GET_ORGANIZATION_FAILED = 'GET_ORGANIZATION_FAILED' as const;

export const RESET_ORGANIZATION = 'RESET_ORGANIZATION' as const;
