export const GET_ORGANIZATION_REQUESTED = 'GET_ORGANIZATION_REQUESTED' as const;
export const GET_ORGANIZATION_SUCCEEDED = 'GET_ORGANIZATION_SUCCEEDED' as const;
export const GET_ORGANIZATION_FAILED = 'GET_ORGANIZATION_FAILED' as const;

export const GET_ENHETSREGISTERET_ORGANIZATION_REQUESTED =
  'GET_ENHETSREGISTERET_ORGANIZATION_REQUESTED' as const;
export const GET_ENHETSREGISTERET_ORGANIZATION_SUCCEEDED =
  'GET_ENHETSREGISTERET_ORGANIZATION_SUCCEEDED' as const;
export const GET_ENHETSREGISTERET_ORGANIZATION_FAILED =
  'GET_ENHETSREGISTERET_ORGANIZATION_FAILED' as const;

export const GET_ORGANIZATION_RATING_REQUESTED =
  'GET_ORGANIZATION_RATING_REQUESTED' as const;
export const GET_ORGANIZATION_RATING_SUCCEEDED =
  'GET_ORGANIZATION_RATING_SUCCEEDED' as const;
export const GET_ORGANIZATION_RATING_FAILED =
  'GET_ORGANIZATION_RATING_FAILED' as const;

export const RESET_ORGANIZATION = 'RESET_ORGANIZATION' as const;
