export const GET_ORGANIZATION_REQUESTED = 'GET_ORGANIZATION_REQUESTED' as const;
export const GET_ORGANIZATION_SUCCEEDED = 'GET_ORGANIZATION_SUCCEEDED' as const;
export const GET_ORGANIZATION_FAILED = 'GET_ORGANIZATION_FAILED' as const;

export const GET_ENHETSREGISTERET_ORGANIZATION_REQUESTED = 'GET_ENHETSREGISTERET_ORGANIZATION_REQUESTED' as const;
export const GET_ENHETSREGISTERET_ORGANIZATION_SUCCEEDED = 'GET_ENHETSREGISTERET_ORGANIZATION_SUCCEEDED' as const;
export const GET_ENHETSREGISTERET_ORGANIZATION_FAILED = 'GET_ENHETSREGISTERET_ORGANIZATION_FAILED' as const;

export const GET_CATALOG_RATING_REQUESTED = 'GET_CATALOG_RATING_REQUESTED' as const;
export const GET_CATALOG_RATING_SUCCEEDED = 'GET_CATALOG_RATING_SUCCEEDED' as const;
export const GET_CATALOG_RATING_FAILED = 'GET_CATALOG_RATING_FAILED' as const;

export const GET_ORGANIZATION_DATASETS_REQUESTED = 'GET_ORGANIZATION_DATASETS_REQUESTED' as const;
export const GET_ORGANIZATION_DATASETS_SUCCEEDED = 'GET_ORGANIZATION_DATASETS_SUCCEEDED' as const;
export const GET_ORGANIZATION_DATASETS_FAILED = 'GET_ORGANIZATION_DATASETS_FAILED' as const;

export const LOAD_MORE_ORGANIZATION_DATASETS_REQUESTED = 'LOAD_MORE_ORGANIZATION_DATASETS_REQUESTED' as const;
export const LOAD_MORE_ORGANIZATION_DATASETS_SUCCEEDED = 'LOAD_MORE_ORGANIZATION_DATASETS_SUCCEEDED' as const;
export const LOAD_MORE_ORGANIZATION_DATASETS_FAILED = 'LOAD_MORE_ORGANIZATION_DATASETS_FAILED' as const;

export const GET_ORGANIZATION_DATASET_REQUESTED = 'GET_ORGANIZATION_DATASET_REQUESTED' as const;
export const GET_ORGANIZATION_DATASET_SUCCEEDED = 'GET_ORGANIZATION_DATASET_SUCCEEDED' as const;
export const GET_ORGANIZATION_DATASET_FAILED = 'GET_ORGANIZATION_DATASET_FAILED' as const;

export const RESET_ORGANIZATION = 'RESET_ORGANIZATION' as const;
