export const GET_DATA_SERVICES_REQUESTED = 'GET_DATA_SERVICES_REQUESTED' as const;
export const GET_DATA_SERVICES_SUCCEEDED = 'GET_DATA_SERVICES_SUCCEEDED' as const;
export const GET_DATA_SERVICES_FAILED = 'GET_DATA_SERVICES_FAILED' as const;
