export const GET_PUBLIC_SERVICE_REQUESTED = 'GET_PUBLIC_SERVICE_REQUESTED' as const;
export const GET_PUBLIC_SERVICE_SUCCEEDED = 'GET_PUBLIC_SERVICE_SUCCEEDED' as const;
export const GET_PUBLIC_SERVICE_FAILED = 'GET_PUBLIC_SERVICE_FAILED' as const;
export const RESET_PUBLIC_SERVICE = 'RESET_PUBLIC_SERVICE' as const;
