export const GET_INFORMATION_MODELS_REQUESTED = 'GET_INFORMATION_MODELS_REQUESTED' as const;
export const GET_INFORMATION_MODELS_SUCCEEDED = 'GET_INFORMATION_MODELS_SUCCEEDED' as const;
export const GET_INFORMATION_MODELS_FAILED = 'GET_INFORMATION_MODELS_FAILED' as const;
