export const GET_INFORMATION_MODELS_REQUESTED = 'GET_INFORMATION_MODELS_REQUESTED' as const;
export const GET_INFORMATION_MODELS_SUCCEEDED = 'GET_INFORMATION_MODELS_SUCCEEDED' as const;
export const GET_INFORMATION_MODELS_FAILED = 'GET_INFORMATION_MODELS_FAILED' as const;
export const RESET_INFORMATION_MODELS = 'RESET_INFORMATION_MODELS' as const;

export const GET_INFORMATION_MODELS_RELATIONS_REQUESTED = 'GET_INFORMATION_MODELS_RELATIONS_REQUESTED' as const;
export const GET_INFORMATION_MODELS_RELATIONS_SUCCEEDED = 'GET_INFORMATION_MODELS_RELATIONS_SUCCEEDED' as const;
export const GET_INFORMATION_MODELS_RELATIONS_FAILED = 'GET_INFORMATION_MODELS_RELATIONS_FAILED' as const;
export const RESET_INFORMATION_MODELS_RELATIONS = 'RESET_INFORMATION_MODELS_RELATIONS' as const;
