export const GET_PUBLIC_SERVICES_REQUESTED = 'GET_PUBLIC_SERVICES_REQUESTED' as const;
export const GET_PUBLIC_SERVICES_SUCCEEDED = 'GET_PUBLIC_SERVICES_SUCCEEDED' as const;
export const GET_PUBLIC_SERVICES_FAILED = 'GET_PUBLIC_SERVICES_FAILED' as const;

export const RESET_PUBLIC_SERVICES = 'RESET_PUBLIC_SERVICES' as const;

export const GET_PUBLIC_SERVICES_REQUIRED_BY_REQUESTED = 'GET_PUBLIC_SERVICES_REQUIRED_BY_REQUESTED' as const;
export const GET_PUBLIC_SERVICES_REQUIRED_BY_SUCCEEDED = 'GET_PUBLIC_SERVICES_REQUIRED_BY_SUCCEEDED' as const;
export const GET_PUBLIC_SERVICES_REQUIRED_BY_FAILED = 'GET_PUBLIC_SERVICES_REQUIRED_BY_FAILED' as const;

export const RESET_PUBLIC_SERVICES_REQUIRED_BY = 'RESET_PUBLIC_SERVICES_REQUIRED_BY' as const;

export const GET_PUBLIC_SERVICES_RELATED_BY_REQUESTED = 'GET_PUBLIC_SERVICES_RELATED_BY_REQUESTED' as const;
export const GET_PUBLIC_SERVICES_RELATED_BY_SUCCEEDED = 'GET_PUBLIC_SERVICES_RELATED_BY_SUCCEEDED' as const;
export const GET_PUBLIC_SERVICES_RELATED_BY_FAILED = 'GET_PUBLIC_SERVICES_RELATED_BY_FAILED' as const;

export const RESET_PUBLIC_SERVICES_RELATED_BY = 'RESET_PUBLIC_SERVICES_RELATED_BY' as const;
