export const GET_PUBLIC_SERVICES_REQUESTED = 'GET_PUBLIC_SERVICES_REQUESTED' as const;
export const GET_PUBLIC_SERVICES_SUCCEEDED = 'GET_PUBLIC_SERVICES_SUCCEEDED' as const;
export const GET_PUBLIC_SERVICES_FAILED = 'GET_PUBLIC_SERVICES_FAILED' as const;

export const RESET_PUBLIC_SERVICES = 'RESET_PUBLIC_SERVICES' as const;

export const GET_PUBLIC_SERVICES_RELATIONS_REQUESTED = 'GET_PUBLIC_SERVICES_RELATIONS_REQUESTED' as const;
export const GET_PUBLIC_SERVICES_RELATIONS_SUCCEEDED = 'GET_PUBLIC_SERVICES_RELATIONS_SUCCEEDED' as const;
export const GET_PUBLIC_SERVICES_RELATIONS_FAILED = 'GET_PUBLIC_SERVICES_RELATIONS_FAILED' as const;

export const RESET_PUBLIC_SERVICES_RELATIONS = 'RESET_PUBLIC_SERVICES_RELATIONS' as const;
