name: Verify dev build

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - develop

jobs:
  build-dev-image:
    name: Build and test dev image on PR from dependabot
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/build.yaml@main
    with:
      dockerfile: dev.Dockerfile
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
