name: Test build

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build image if PR from fork
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build.yaml@main
