name: Accessibility tests with Pa11y
on:
  pull_request:
      branches:
        - develop

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies.
        run: npm install
      - name: Create .env
        run: |
          echo "${{ secrets.STAGING_ENV_VARS }}" > .env
      - name: Start server
        run: npm start &
      - name: Wait for server to start
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:3001
      - name: Run pa11y
        run: npm run pa11y-ci
