name: Accessibility tests with Pa11y
on:
  push:
      branches:
        - feat/ha/implement-pa11y-ci

jobs: 
  pa11y-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install 
      - run: npm pa11y-ci https://www.nature.com/

