name: Accessibility tests with Pa11y
on:
  push:
      branches:
        - feat/ha/implement-pa11y-ci

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies.
        run: npm install 
      - name: Start server and run pa11y-ci. 
        run: npm start & sleep 120s && npm run pa11y-ci

