name: Accessibility tests with Pa11y
on:
  push:
      branches:
        - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies.
        run: npm install
      - name: Run pa11y
        run: npm run pa11y-ci

